### ISSUE TITLE
简历中描述有个问题，不知道已经修改没有

### ISSUE THREAD

**Issue by tang6922718** [junlinsir/junlinsir.github.io#1]
该项目主要分为网站前台、运营商后台、商家管理后台三个子系统，采用了SOA架构，采用前后端分离的**开始**方式。   @junlinsir

**Comment by junlinsir** [comment]
已修改，感谢！

**Comment by junlinsir** [comment]
> 该项目主要分为网站前台、运营商后台、商家管理后台三个子系统，采用了SOA架构，采用前后端分离的**开始**方式。 @junlinsir

已修改，感谢！
